### ISSUE TITLE
Training data generation

### ISSUE THREAD

**Issue by laol777** [francescopittaluga/invsfm#2]
Hello, is it possible to release code, which capable to generate train data from original datasets? And asking in advance: how hard to adapt it to my custom dataset? Thanks

**Comment by francescopittaluga** [comment]
I used [COLMAP](https://colmap.github.io/) to generate the SFM models and depth maps (The default COLMAP parameters should work just fine). Once you run COLMAP on your dataset, [demo_colmap.py](https://github.com/francescopittaluga/invsfm/blob/master/demo_colmap.py) shows how to extract the training data for this project.

**Comment by laol777** [comment]
I should convert ppm format into jpg in order to make COLMAP work? COLMAP provides SIFT features?

**Comment by francescopittaluga** [comment]
COLMAP works with ppm, but my code does not. Yes, COLMAP does provide SIFT features (See [demo_colmap.py](https://github.com/francescopittaluga/invsfm/blob/master/demo_colmap.py))
