### ISSUE TITLE
Ask for the requirements

### ISSUE THREAD

**Issue by zhoux121** [francescopittaluga/invsfm#4]
Hi
Could you please provide the tensorflow version?
![image](https://user-images.githubusercontent.com/21269237/120901884-5ea8e900-c60b-11eb-8ed0-a90dd5173da0.png)

Thank you so much

**Comment by kunalchelani** [comment]
Hi @zhoux121, I had run into similar problems when I first used it. I think this has to do with one of the sorting functions which has changed implementation in later versions of tensorflow. I could only get it working with `tf 1.10` as  mentioned in the README.

**Comment by francescopittaluga** [comment]
Tensorflow 1.10
